// import { useRouter } from 'next/router'
import Head from 'next/head'
import useSWR from 'swr'
import { getAccessToken, getUserData } from '../src/services/spotify'
import { Home } from '../src/components/Home'
import { Login } from '../src/components/login'
import firebaseInit from '../src/services/firebase'

firebaseInit()

// saveTagsOnFirestore()

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function HomePage({ access_token, userId }) {
  const { data, error } = useSWR('/api/top-tracks', fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  return (
    <>
      <Head>
        <title>Band Tag | Log In</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {access_token ? (
        <Home user={userId} tracks={data.severalTopTracks} />
      ) : (
        <Login />
      )}
    </>
  )
}

export async function getStaticProps() {
  const response = await getAccessToken()
  const { access_token } = response

  const responseUser = await getUserData()
  const { id } = responseUser

  return {
    props: {
      access_token: JSON.stringify(access_token),
      userId: id
    }
  }
}
